development:
  dialect: mysql
  datasource: root:123456@tcp(127.0.0.1:3306)/mydb?parseTime=true
  dir: migrations/schema
  table: migrations
  # ${DB_USER}:${DB_PASS}@tcp(127.0.0.1:${DB_PORT})/${DB_NAME}?parseTime=true