version: '3'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
volumes:
  db: