
-- +migrate Up
CREATE TABLE IF NOT EXISTS`order`(
  orderId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  cartId INT NOT NULL,
  subTotal FLOAT NOT NULL,
  timeCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- +migrate Down
DROP TABLE IF EXISTS `order`;
